/* Let's create an array to store music details */
let allMusic = [
    // {
    //   name: " Koumpentoum: Périodes de semences",
    //   date: "04/06/semaine 2",
    //   img: "music-1",
    //   src: "music-1",
    //   audio_src: "",
    //   pdf_src: "",
    //   type: "agro",
    //   month: "Juillet",
    //   semaine: "semaine 2",
    //   zone: "Koumpentoum"
    // },
    // {
    //     name: "Koumpentoum: Utilisation d'angrais",
    //     date: "04/08/2020",
    //     img: "music-2",
    //     src: "music-2",
    //     audio_src: "",
    //     pdf_src: "",
    //     type: "agro",
    //     month: "Août",
    //     semaine: "semaine 2",
    //     zone: "Koumpentoum"  
    //   },
    //   {
    //     name: "DaguaBirame: Description conseil",
    //     date: "04/09/2020",
    //     img: "music-3",
    //     src: "music-3",
    //     audio_src: "",
    //     pdf_src: "",
    //     type: "agro",
    //     month: "Août",
    //     semaine: "semaine 2",
    //     zone: "Dagua-Birame"  
    //   },
    //   {
    //     name: "DaguaBirame: Description conseil",
    //     date: "04/10/2020",
    //     img: "music-4",
    //     src: "music-4",
    //     audio_src: "",
    //     pdf_src: "",
    //     type: "agro",
    //     month: "Septembre",
    //     semaine: "semaine 2",
    //     zone: "Dagua-Birame"  
    //   },
    //   {
    //     name: "DaguaBirame: Description conseil",
    //     date: "04/05/2020",
    //     img: "music-5",
    //     src: "music-5",
    //     audio_src: "",
    //     pdf_src: "",
    //     type: "agro",
    //     month: "Septembre",
    //     semaine: "semaine 2",
    //     zone: "Dagua-Birame"  
    //   },
    //   {
    //     name: "Koumpentoum: Description conseil",
    //     date: "04/05/2020",
    //     img: "music-6",
    //     src: "music-6",
    //     audio_src: "",
    //     pdf_src: "",
    //     type: "livestock",
    //     month: "Juillet",
    //     semaine: "semaine 2",
    //     zone: "Koumpentoum"  
    //   },
    //   {
    //     name: "Koumpentoum: Description conseil",
    //     date: "04/05/2020",
    //     img: "music-7",
    //     src: "music-7",
    //     audio_src: "",
    //     pdf_src: "",
    //     type: "livestock",
    //     month: "Août",
    //     semaine: "semaine 2",
    //     zone: "Koumpentoum"  
    //   },
    //   {
    //     name: "Dagua-Birame: Description conseil",
    //     date: "04/05/2020",
    //     img: "music-8",
    //     src: "music-8",
    //     audio_src: "",
    //     pdf_src: "",
    //     type: "livestock",
    //     month: "Août",
    //     semaine: "semaine 2",
    //     zone: "Dagua-Birame"  
    //   },
    //   {
    //     name: "Dagua-Birame: Description conseil",
    //     date: "04/05/2020",
    //     img: "music-9",
    //     src: "music-9",
    //     audio_src: "",
    //     pdf_src: "",
    //     type: "livestock",
    //     month: "Septembre",
    //     semaine: "semaine 2",
    //     zone: "Dagua-Birame"  
    //   },
    //   {
    //     name: "Dagua-Birame: Description conseil",
    //     date: "04/05/2020",
    //     img: "music-10",
    //     src: "music-10",
    //     audio_src: "",
    //     pdf_src: "",
    //     type: "livestock",
    //     month: "Septembre",
    //     semaine: "semaine 2",
    //     zone: "Dagua-Birame"  
    //   },
    //   {
    //     name: " Dahra: Périodes de semences",
    //     date: "04/06/semaine 2",
    //     img: "music-11",
    //     src: "music-11",
    //     audio_src: "",
    //     pdf_src: "",
    //     type: "agro",
    //     month: "Juillet",
    //     semaine: "semaine 1",
    //     zone: "Dahra"
    //   },
    //   {
    //       name: "Kaolack: Utilisation d'angrais",
    //       date: "04/08/2020",
    //       img: "music-12",
    //       src: "music-12",
    //       audio_src: "",
    //       pdf_src: "",
    //       type: "agro",
    //       month: "Août",
    //       semaine: "semaine 1",
    //       zone: "Kaolack"  
    //     },
    //     {
    //       name: "Linguère: Description conseil",
    //       date: "04/09/2020",
    //       img: "music-13",
    //       src: "music-13",
    //       audio_src: "",
    //       pdf_src: "",
    //       type: "agro",
    //       month: "Août",
    //       semaine: "semaine 1",
    //       zone: "Linguère"  
    //     },
    //     {
    //       name: "Meouane: Description conseil",
    //       date: "04/10/2020",
    //       img: "music-14",
    //       src: "music-14",
    //       audio_src: "",
    //       pdf_src: "",
    //       type: "agro",
    //       month: "Septembre",
    //       semaine: "semaine 4",
    //       zone: "Meouane"  
    //     },
    //     {
    //       name: "Meouane: Description conseil",
    //       date: "04/05/2020",
    //       img: "music-15",
    //       src: "music-15",
    //       audio_src: "",
    //       pdf_src: "",
    //       type: "agro",
    //       month: "Septembre",
    //       semaine: "semaine 2",
    //       zone: "Meouane"  
    //     },
    //     {
    //       name: "Meouane: Description conseil",
    //       date: "04/05/2020",
    //       img: "music-16",
    //       src: "music-16",
    //       audio_src: "",
    //       pdf_src: "",
    //       type: "livestock",
    //       month: "Juillet",
    //       semaine: "semaine 2",
    //       zone: "Meouane"  
    //     },
    //     {
    //       name: "Meouane: Description conseil",
    //       date: "04/05/2020",
    //       img: "music-17",
    //       src: "music-17",
    //       audio_src: "",
    //       pdf_src: "",
    //       type: "livestock",
    //       month: "Août",
    //       semaine: "semaine 2",
    //       zone: "Meouane"  
    //     },
    //     {
    //       name: "Thiel: Description conseil",
    //       date: "04/05/2020",
    //       img: "music-18",
    //       src: "music-18",
    //       audio_src: "",
    //       pdf_src: "",
    //       type: "livestock",
    //       month: "Août",
    //       semaine: "semaine 2",
    //       zone: "Thiel"  
    //     },
    //     {
    //       name: "Thiel: Description conseil",
    //       date: "04/05/2020",
    //       img: "music-19",
    //       src: "music-19",
    //       audio_src: "",
    //       pdf_src: "",
    //       type: "livestock",
    //       month: "Septembre",
    //       semaine: "semaine 2",
    //       zone: "Thiel"  
    //     },
        // {
        //   name: "Thiel: Description conseil",
        //   date: "04/05/2020",
        //   img: "music-20",
        //   src: "music-20",
        //   audio_src: "",
        //   pdf_src: "",
        //   type: "livestock",
        //   month: "Septembre",
        //   semaine: "semaine 2",
        //   zone: "Thiel"  
        // },
        {
          name: "Ferlo Ouest: CoP AICCRA ",
          date: "19/08/2024",
          img: "music001",
          src: "music001",
          audio_src: "",
          pdf_src: "",
          type: "livestock",
          year: " 2024",
          month: "Août",
          semaine: "semaine 3",
          zone: "Ferlo Ouest"  
        },
        {
          name: "Thiel: iSAT ",
          date: "26/08/2024",
          img: "music002",
          src: "music002",
          audio_src: "",
          pdf_src: "",
          type: "agro",
          year: " 2024",
          month: "Août",
          semaine: "semaine 4",
          zone: "Thiel"  
        },
        {
          name: "Meouane: iSAT ",
          date: "26/08/2024",
          img: "music003",
          src: "music003",
          audio_src: "",
          pdf_src: "",
          type: "agro",
          year: " 2024",
          month: "Août",
          semaine: "semaine 4",
          zone: "Meouane"  
        },
        {
          name: "Kaolack: iSAT ",
          date: "26/08/2024",
          img: "music004",
          src: "music004",
          audio_src: "",
          pdf_src: "",
          type: "agro",
          year: " 2024",
          month: "Août",
          semaine: "semaine 4",
          zone: "Kaolack"  
        },
        {
          name: "Koumpemtoum: iSAT ",
          date: "26/08/2024",
          img: "music005",
          src: "music005",
          audio_src: "",
          pdf_src: "",
          type: "agro",
          year: " 2024",
          month: "Août",
          semaine: "semaine 4",
          zone: "Koumpemtoum"  
        },
        {
          name: "Dagua Biram: iSAT ",
          date: "26/08/2024",
          img: "music006",
          src: "music006",
          audio_src: "",
          pdf_src: "",
          type: "agro",
          year: " 2024",
          month: "Août",
          semaine: "semaine 4",
          zone: "Dagua Biram"  
        },
        //   name: "Cluster: ",
        //   date: "20/08/2024",
        //   img: "music-22",
        //   src: "music-22",
        //   audio_src: "",
        //   pdf_src: "",
        //   type: "livestock",
        //   month: "Août",
        //   semaine: "semaine 3",
        //   zone: "Cluster"  
        // },
        // {
        //   name: "Cluster: ",
        //   date: "20/08/2024",
        //   img: "music-23",
        //   src: "music-23",
        //   audio_src: "",
        //   pdf_src: "",
        //   type: "livestock",
        //   month: "Août",
        //   semaine: "semaine 3",
        //   zone: "Cluster"  
        // },
        // {
        //   name: "Cluster: ",
        //   date: "20/08/2024",
        //   img: "music-24",
        //   src: "music-24",
        //   audio_src: "",
        //   pdf_src: "",
        //   type: "livestock",
        //   month: "Août",
        //   semaine: "semaine 3",
        //   zone: "Cluster"  
        // },
        // {
        //   name: "Cluster: ",
        //   date: "20/08/2024",
        //   img: "music-25",
        //   src: "music-24",
        //   audio_src: "",
        //   pdf_src: "",
        //   type: "livestock",
        //   month: "Août",
        //   semaine: "semaine 3",
        //   zone: "Cluster"  
        // }
]


// let allMusic = [
  
//   {
//     name: "Cluster: ",
//     date: "20/08/2024",
//     img: "music-21",
//     src: "music-21",
//     audio_src: "",
//     pdf_src: "",
//     type: "livestock",
//     month: "Août",
//     semaine: "semaine 3",
//     zone: "Cluster"  
//   },
//   {
//     name: "Cluster: ",
//     date: "20/08/2024",
//     img: "music-22",
//     src: "music-22",
//     audio_src: "",
//     pdf_src: "",
//     type: "livestock",
//     month: "Août",
//     semaine: "semaine 3",
//     zone: "Cluster"  
//   },
//   {
//     name: "Cluster: ",
//     date: "20/08/2024",
//     img: "music-23",
//     src: "music-23",
//     audio_src: "",
//     pdf_src: "",
//     type: "livestock",
//     month: "Août",
//     semaine: "semaine 3",
//     zone: "Cluster"  
//   },
//   {
//     name: "Cluster: ",
//     date: "20/08/2024",
//     img: "music-24",
//     src: "music-24",
//     audio_src: "",
//     pdf_src: "",
//     type: "livestock",
//     month: "Août",
//     semaine: "semaine 3",
//     zone: "Cluster"  
//   },
//   {
//     name: "Cluster: ",
//     date: "20/08/2024",
//     img: "music-25",
//     src: "music-24",
//     audio_src: "",
//     pdf_src: "",
//     type: "livestock",
//     month: "Août",
//     semaine: "semaine 3",
//     zone: "Cluster"  
//   }

// ]